### ISSUE TITLE
Simple example to understand how to use PDDL4J

### ISSUE THREAD

**Issue by moguxedar** [pellierd/pddl4j#16]
Hi,
 
I would like to use your Java planning tool (PDDL4J) as a library (i.e. invoking directly its classes from my Java program) and I should just need to pass it the domain description and the problem description and then to invoke a planner.
 
Is there a straightforward way to do this?
 
I tried to find an example in order to understand how to do this but I only found an example (in the [sourceforge release](https://sourceforge.net/projects/pdd4j/files/pdd4j/version%201.0/PDDL4J-v1.0.tar.gz/download)) that works with version 1.0 of the tool and that is “incompatible” with the new version (3.5.0). In the GitHub repository, as far as I can see, there are no examples (and this seems quite strange to me). There is one in the [Wiki](https://github.com/pellierd/pddl4j/wiki/Getting-Started#simple-problem-solving) but it works only "stand-alone" and it doesn't work when I integrate it in my Java code (I don't want to build it with Gradle, for this reason I'm using the JAR, and I don't want to run it as a Java agent)
 
Could you tell me if and where I can find it, please?
(also a brief snippet will be enough for my purposes)
 
Thanks

**Comment by moguxedar** [comment]
Just to clarify my question.

In your README there is written:

> PDDL4J is an open source library under LGPL license.

But in all the examples on your webpages and wiki (at least the ones that I've found), you use it as a "stand-alone solver".

Is it possible to use it in the following way?

```
// my code
// Select and initialize the planner
// Specify the "domain" and the "problem" to the planner
// Execute the planner and get the output
// my code
```

Thanks

**Comment by pellierd** [comment]
To use PDDL4J as library just add the library to your classpath and add the option -javaagent to the JVM when you launch your program:
> java -javaagent:pddl4j-version.jar .....

To call a planner directly in your code follow the example given on the [wiki page](https://github.com/pellierd/pddl4j/wiki/Getting-Started#simple-problem-solving).

The JVM option is used to get statistics on the memory used by the JVM during search. It is based on the [instrument API](https://docs.oracle.com/javase/8/docs/api/java/lang/instrument/package-summary.html) proposed by java since SDK 1.5.

If you don't want to use the agent option, you have to write your own version of the planner by removing all the calls to the class [fr.uga.pddl4j.util.MemoryAgent](https://github.com/pellierd/pddl4j/blob/master/src/main/java/fr/uga/pddl4j/util/MemoryAgent.java) from the code of the planner you want to use. Have a look to the [HSP planner](https://github.com/pellierd/pddl4j/blob/master/src/main/java/fr/uga/pddl4j/planners/hsp/HSP.java) for instance.

**Comment by moguxedar** [comment]
Thanks for your answer.

Actually I would like to integrate PDDL4J into another library and I don't want to "force" my users to use the option ` -javaagent` (given that some of them cannot use it, for instance the users that want to use my library on Android)

I'll try your second suggestion, but it seems quite "complex" for my purposes (I was looking for a Java library that allows me to parse and execute PDDL programs because I don't want to do it by myself).

Thanks
