### ISSUE TITLE
Wiki not updated

### ISSUE THREAD

**Issue by DangerBlack** [pellierd/pddl4j#18]
Old Code in the wiki
```
// Parse the domain and the problem
      ErrorManager errorManager = factory.parseString(domain, problem);
      if (!errorManager.isEmpty()) {
            errorManager.printAll();
            System.exit(0);
      }
```
Need to be fixed like this.
```
// Parse the domain and the problem
      ErrorManager errorManager;
      try{        
        errorManager = factory.parse(domain, problem);
        if (!errorManager.isEmpty()) {
                errorManager.printAll();
                System.exit(0);
          }
      }catch(IOException e){
          
      }
```

Despite this the function
```
planner.search(pb);
```
trigger an error:

Exception in thread "main" java.lang.IllegalStateException: Instrumentation environment not initialised.
	at fr.uga.pddl4j.util.MemoryAgent.sizeOf(MemoryAgent.java:152)
	at fr.uga.pddl4j.util.MemoryAgent.deepSizeOf(MemoryAgent.java:190)
	at fr.uga.pddl4j.util.MemoryAgent.deepSizeOf(MemoryAgent.java:170)
	at fr.uga.pddl4j.planners.hsp.HSP.search(HSP.java:241)
	at provapddl.ProvaPDDL.main(ProvaPDDL.java:149)

**Comment by pellierd** [comment]
Two comments:

1. You are right the line 
`errorManager = factory.parse(domain, problem);`
throws an IOException.  But it makes no sens to let the catch block empty. It just hides the error when reading the domain or the problem.  It is not a good Java Programming habit. I will not change it.

2. The exception IllegalStateException is thrown by the call
`planner.search(pb);`
because you forget to indicate to the JVM the java agent to use to monitor the memory usage. The commande to use is :
` java -javaagent:build/libs/pddl4j-VERSION.jar -server -Xms2048m -Xmx2048m fr.uga.pddl4j.planners.hsp.HSP -o <DOMAIN FILE PATH> -f <PROBLEM FILE PATH>`

Please read carefully the [Get started section](https://github.com/pellierd/pddl4j/wiki/Getting-Started).

**Comment by DangerBlack** [comment]
```factory.parseString(domain, problem);```
Is no more available in your code!

factory.parse(domain, problem);

**Comment by pellierd** [comment]
I will change it.

Thanks
