### ISSUE TITLE
Planner finds solution to unsatisfiable problem

### ISSUE THREAD

**Issue by maghid** [pellierd/pddl4j#42]
Hi,
I have a domain and a problem for it which has a 2 goals (a conjunction of predicates).
When one of the 2 goals becomes unsatisfiable, the planner should not find any solution. However, it does find a plan, considering only the other goal and ignoring the one which is unsatisfiable.
I have the attached the domain files and the problem files.
If I give them in input to this planner: http://editor.planning.domains/# it (correctly) says no plan can solve the problem.
However pddl4j finds the following solution: `move-to banca gelateria p21 p22 `, which satisfies only the second goal. The first one (which is unsatisfiable) is ignored. These are the files corresponding to this case:
[domain1.txt](https://github.com/pellierd/pddl4j/files/1920649/domain1.txt)
[problem1.txt](https://github.com/pellierd/pddl4j/files/1920651/problem1.txt)
If the second goal is satisfied, then it returns an empty plan but does not fail. These are the files corresponding to this case:
[domain2.txt](https://github.com/pellierd/pddl4j/files/1920650/domain2.txt)
[problem2.txt](https://github.com/pellierd/pddl4j/files/1920652/problem2.txt)

I have also added a brief explanation of the domain/problems below in case it helps.

Thank you!

_Details about the problem:_
The domain modeled is a small town where a person has to perform some tasks. The 2 goals of the problem are: 
1. be at the bank (banca) at 10am: predicate `(be-at banca p20)`, where p20 means 10am
2. for the final state, the person has to be at the ice-cream parlor (gelateria): predicate `(be gelateria)`

In the first case, in the initial state I have the predicates `(be-at gelateria p20)`, `(now p21)` and` (be-at banca p21) `(indicating I was at 10am at the ice-cream parlor, and now it is 10.30am and I am at the bank). There should be no solution. PDDL4J instead finds a solution with an action which satisfies only the second goal (move to the ice-cream parlor).

In the second case, in the initial state I have the predicates `(be-at gelateria p20)` and `(be gelateria)`, indicating I was at the ice-cream parlor at 10am and I am at the ice-cream parlor right now. The second goal is satisfied, but the first one is impossible: PDDL4J returns a plan with no actions but does not fail.

**Comment by ehermellin** [comment]
Hi @maghid, 
Thanks you for using PDDL4J for your project. As you provide files and explanation, i will investigate your issue !
Best regards, 
Emmanuel.

**Comment by maghid** [comment]
The planner used is HSP, but I also tested with the web app (http://pddl4j.imag.fr/remote/app/) and the other 2 planners (EHC and FF) and it seems to give the same results.
If you require any further information, let me know.
Thank you,
Margherita

**Comment by ehermellin** [comment]
Thanks for your reply.
The webapp still running PDDL4J 3.5.0 and the next version is 3.6.0 on the Github repo. As the result is the same for both, i will read your files and try to explain what's happen !
Have a good day, 
Emmanuel.

**Comment by ehermellin** [comment]
Hi @maghid,

> "If the second goal is satisfied, then it returns an empty plan but does not fail."

 The fact that PDDL4J provides an empty plan is a well known issue which are not resolved for the moment in PDDL4J v3.6.0. We need to work on this, sorry for the inconveninence brought by this issue.

About the first case, the problem comes from the modeling made in your domain.pddl file. Indeed, after reviewing your pddl files, I noticed some inconsistencies :

- "move-to" and "drive-to" are moving actions, but there time preconditions are different (now, next and future for "move-to" and only now for "drive-to"). Same for effects.
- the predicate be-at is not an effect but a precondition (in my opinion)
- (not (be-at ...)) is never called

Your way of modeling time is very smart but there are errors in the way your actions are modeled (preconditions and effects).

I advise you to create a very simple domain with an action and if the behavior is good to incrementally add the other actions.

Feel free to ask, if you need some help or if you have some questions.

Best regads, 
Emmanuel.

**Comment by maghid** [comment]
Hello @ehermellin ,

Thank you very much for your help.
I will follow your advice and try to determine if the problem is caused by the domain.

Have a good day,
Margherita.

**Comment by maghid** [comment]
Hi @ehermellin,

Changing the preconditions did indeed fix the problem. Thank you very much for your help!

**Comment by ehermellin** [comment]
Hi @maghid 

Glad to have been able to help you !

Best regards, 

Emmanuel.
