### ISSUE TITLE
BitState to BitExp

### ISSUE THREAD

**Issue by git-interface** [pellierd/pddl4j#47]
Hello,
First of all great job this is an excellent library. I have been trying to understand the library and a came up with a silly question. Is an easy way to convert BitState to bit BitExp?

**Comment by ehermellin** [comment]
Hi, 
Thanks you for using PDDL4J. We are glad that it is useful to you.

BitExp: A bit set expression is used to encode preconditions (negative and positive) but also effects of the instantiated operators. So a BitExp has two BitVector (a negative one and a positive one).

BitState: A BitState is less generic compare to a BitExp because it has only one BitVector (the positive one).

To create a BitExp from a BitState nothing to do: the positive facts of the specified expression are added to this state and the negative ones are delete.

```
/**
* Creates a new state from a specified <code>BitExp</code>.
*
* @param exp the <code>BitExp</code> that represents the logical state.
*/
public BitState(final BitExp exp) {
  this();
  if (exp == null) {
     throw new NullPointerException("exp == null");
  }
  this.or(exp.getPositive());
  this.andNot(exp.getNegative());
}
```

To convert a BitState to a BitExp, it is necessary to create a complementary vector that contains the negative part. It could be done with BitSet operator.

`BitExp(BitVector positive, BitVector negative)`

Best Regards,

Emmanuel.

**Comment by pellierd** [comment]
BitState is the class to be use when you make the closed world assumption

**Comment by git-interface** [comment]
thank you so much, that was very helpful
