### ISSUE TITLE
Get all solution plans

### ISSUE THREAD

**Issue by MatteoLuongo20020107** [pellierd/pddl4j#56]
Hi,
I need to recover all the solution plans for a pddl problem.
If I use the search method I get a solution plan, ok.

But if I try to use the getSolutionPlans (codeproblem) method defined in AbstractStateSpacePlannerAnytime I get an empty Vector <Plan>.

Can someone give me some information or show me some examples?

Thanks in advance

**Comment by ehermellin** [comment]
Hi Matteo,

First, we want to thank you for using PDDL4J v3.8.

To recover all the solution plans, you need to use anytime planners (FFAnytime or HCAnytime) or the generic anytime planner with the anytime search strategy of your choice: 

```java
StateSpacePlanner planner = plannerFactory.getPlanner(Planner.Name.FFAnytime, (int) timeout, heuristic, weight, true, 1);

StateSpacePlanner planner = new GenericAnytimePlanner(true, 1, new AStarAnytime((int) timeout, heuristic, weight));

StateSpacePlanner planner = new GenericAnytimePlanner(true, 1, new GreedyBestFirstSearchAnytime((int) timeout, heuristic, weight));
```

Then, you need to use the search method to launch the resolution of the PDDL problem. During the resolution of the problem, the PDDL4J library will notify each solution found in the LOG.  At this time, you can try to recover the solution plans by getting the Vector:

```java
GreedyBestFirstSearchAnytime searchStrategy = new GreedyBestFirstSearchAnytime((int) timeout, heuristic, weight)
GenericAnytimePlanner planner = new GenericAnytimePlanner(true, 1, searchStrategy);

/**/

Vector solutionPlans = searchStrategy.getSolutionNodes();
```

Be carefull, if you want to recover the solutions dynamically during the resolution of the problem, it is necessary to make sure that PDDL4J does not execute in the same thread as your program which will get the solution Vector.
If you just want to get all the solution plans at the end, you don't have to deal with another thread.

However, the best way to recover solutions is to use events: see the [Wiki](https://github.com/pellierd/pddl4j/wiki/Getting-Started#how-to-use-solutionevent-and-solutionlistener-since-pddl4j-373).

You can look at unit tests on anytime features, this will give you examples of how to recover the solutions.

Best Regards, 
Emmanuel.
