### ISSUE TITLE
PDDL4J unable to solve high arity predicates and actions?

### ISSUE THREAD

**Issue by faizan-m** [pellierd/pddl4j#73]
Hi!

Using the files attached here:
[domain.txt](https://github.com/pellierd/pddl4j/files/4441696/domain.txt)
[problem.txt](https://github.com/pellierd/pddl4j/files/4441697/problem.txt)

A solution can be found using other planners including the online one [here](https://web-planner.herokuapp.com/).

I am running the source code directly in an IDE to help debug. I think I have chased the problem down to the CodedProblem being generated not having the correct goal state. The only thing weird about the predicate and action here is that they have very high arity. 

Will appreciate any help in figuring this out further!

**Comment by pellierd** [comment]
Could you clarify the problem? Is the problem related to encoding or searching? If it's during search, which planner do you use? Do you get an error message?

**Comment by faizan-m** [comment]
Problem Observed:
When the given files are used, PDDL4J returns an empty plan (no failures). The parameters for what searching algorithms to use does not make a difference. The correct solution is non-empty and can be generated by the online website planner linked.

Possible Cause:
I stepped through the code to see why it was behaving this way and I noticed that the CodedProblem being generated did not seem to have a proper goal state. So I am guessing the problem is somewhere in the encoding step.

**Comment by pellierd** [comment]
The encoding does not generate actions with 2 identical parameters. The solution plan of  your problem is :
`
0: (craft wood ca iron cb air cc axe cres air) [0]
`

This makes the search not complete, but in most cases allows to delete actions that are of no interest. We will add an option to enable or disable this in the future.

To solve your problem use the code of the HDDL  branch or comment the line 138 of class fr.uga.pddl4j.encoding.Instantiation.
