### ISSUE TITLE
Empty plan

### ISSUE THREAD

**Issue by rumster** [pellierd/pddl4j#8]
Hi,

First, I want to thank you for developing and maintaining this package. A stable OS-independent planner is really useful for building applications on top of.

I may be missing something (I have little practical experience with planners) but I think the attached files demonstrate a bug. The planner reports an empty plan for "-o bug.pddl -f p01.pddl" even though the initial state is empty and the goal contains one fact. Adding another fact to the goal ("-o bug.pddl -f p02.pddl") produces a two step plan as expected.

Roman

[bug.zip](https://github.com/pellierd/pddl4j/files/189733/bug.zip)

**Comment by cegerard** [comment]
I have found the problem. In fact it is not really a bug.

**Comment by rumster** [comment]
Can you please explain it to me?
Thanks,
Roman

**Comment by cegerard** [comment]
We newly introduced plan object as output and the HSP planner use a SequentialPlan.
A SequentialPlan is define on top off operators (And, etc.), on your first problem you only have one final state to match for your object a. So that does not match SequentialPlan implementation.

Because you use the AND operator on your second problem the planner work correctly.

So we encounter a problem with SequentialPlan, cause now we does not support goal with only one predicate.

**Comment by rumster** [comment]
I'm afraid I don't follow.
Is this the standard behavior for planners supporting PDDL or is this a limitation of pddl4j?
Is there a workaround?

The original problem had an 'and' with several facts (-o sll-domain.pddl -f acyclic-sll-5.pddl).

[heap.zip](https://github.com/pellierd/pddl4j/files/189983/heap.zip)

**Comment by pellierd** [comment]
The bug is now corrected in the devel branch. The bug was due to a condition when considering empty goal in the encoder of the library. You can now use an only proposition in goal description.

**Comment by rumster** [comment]
Have you committed the fix? The devel branch looks the same.
Also, the heap.zip example shows that the problem happens also when the goal contains multiple facts. I tried adding multiple unsatisfied goals but the behavior seems the same.

Again, thanks for the quick response.

**Comment by rumster** [comment]
Thanks! That solved the problem.
